# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logexample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='null', max_length=100, verbose_name='모델명')),
                ('func', models.CharField(default='null', max_length=100, verbose_name='함수명')),
                ('subc', models.CharField(default='null', max_length=100, verbose_name='하위클래스')),
                ('scene', models.CharField(default='null', max_length=100, verbose_name='씬이름')),
                ('hash', models.CharField(default='OCYXS5K', max_length=32, verbose_name='API키')),
                ('regdate', models.DateTimeField(default=datetime.date.today, verbose_name='등록일시')),
                ('update', models.DateTimeField(default=datetime.date.today, verbose_name='갱신일시')),
                ('isml', models.BooleanField(default=True, verbose_name='머신러닝여부')),
            ],
        ),
    ]
