# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logexample',
            new_name='mlspec',
        ),
    ]
