# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0019_auto_20170925_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, verbose_name='발송 시각')),
                ('q', models.CharField(max_length=1000, verbose_name='질문')),
                ('qstar', models.CharField(default='null', max_length=30, verbose_name='Q결과평점')),
                ('qgnrs', models.CharField(default='null', max_length=30, verbose_name='Q장르Top3')),
                ('a', models.CharField(max_length=1000, verbose_name='응답')),
                ('astar', models.CharField(default='null', max_length=30, verbose_name='A결과평점')),
                ('agnrs', models.CharField(default='null', max_length=30, verbose_name='A장르Top3')),
                ('isgen', models.BooleanField(default=False, verbose_name='응답생성여부')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
