# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='appname',
            field=models.CharField(default='null', max_length=30, verbose_name='앱이름'),
        ),
    ]
