# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_uploadfile_appname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='NewApp',
        ),
    ]
