# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_auto_20171015_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y%m%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='NewApp',
        ),
    ]
