# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20171015_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCsharp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y%m%d/')),
                ('apikey', models.CharField(default='null', max_length=30, verbose_name='앱apikey')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.RemoveField(
            model_name='newapp',
            name='file',
        ),
        migrations.AddField(
            model_name='newapp',
            name='appname',
            field=models.CharField(default='null', max_length=30, verbose_name='앱이름'),
        ),
        migrations.AddField(
            model_name='newapp',
            name='update',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='등록일시'),
        ),
    ]
