# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_auto_20171019_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='apikey',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='APIkey'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='appname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='앱이름'),
        ),
    ]
