# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20171020_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='logexample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='null', max_length=1000, verbose_name='data')),
                ('ip', models.CharField(default='null', max_length=100, verbose_name='ipaddr')),
                ('country', models.CharField(default='null', max_length=32, verbose_name='location')),
                ('regdate', models.DateTimeField(default=datetime.date.today, verbose_name='등록일시')),
            ],
        ),
    ]
