# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_logexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csfile',
            name='file',
            field=models.CharField(default='null', max_length=100, verbose_name='파일이름'),
        ),
    ]
